### 基础模块的导入

In [48]:
from __future__ import print_function

import os
import sys
# 使用insert 0即只使用github，避免交叉使用了pip安装的abupy，导致的版本不一致问题
sys.path.insert(0, os.path.abspath('../'))
import abupy
# 使用沙盒数据
abupy.env.enable_example_env_ipython()

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0)

ValueError: source code string cannot contain null bytes

In [ ]:
print(sys.version)

# 第3章 量化工具-Numpy

[<h1>极客营</h1>](http://igeekhome.com) 
numpy是python很多科学计算和工程库的基础库，在量化数据分析中最常使用pandas也是基于numpy的封装。

## 3.1 并行化思想与基础操作
习惯以及推引用numpy的方式如下：

In [2]:
import numpy as np

### 3.1.1  并行化思想
首先我们先看一下，构建10000个元素的普通列表，循环求解里面每一个元素的平方，使用%time看看执行效率

In [3]:
%timeit [i**2 for i in range(100)]

25.5 µs ± 552 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


我们再看看，使用np.arange()构建数组的执行效率

In [ ]:
np_list = np.arange(100)
%timeit np_list**2

numpy数组和普通列表的操作方式也是不同的，numpy通过广播机制作用于每一个内部元素，是一种并行化执行的思想，普通列表则作用于整体。示例如下

In [ ]:
np_list.shape

In [ ]:
mlist = [
    [(255,255,255),(255,125,125)],
    [(255,255,255),(255,125,125)]
]
img=np.array(mlist)

In [ ]:
img.shape

In [4]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
np.empty((5,5))

array([[ 2.68156159e+154,  2.68156159e+154,  6.42285340e-323,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  2.68156159e+154, -4.33333805e-311,
         2.47032823e-323,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  2.68156159e+154,
        -1.49457317e-154,  9.88131292e-324]])

In [11]:
## 创建一只服从正态分布的股票 200支 504天的交易数据

stock_count = 200
view_days = 504

stock_data = np.random.standard_normal((stock_count,view_days))

In [13]:
stock_data.shape

(200, 504)

In [17]:
array = np.zeros((10,10))

In [15]:
## 将第三列的数据全部改为1

In [18]:
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
array[:,2:3] = 3

In [20]:
array

array([[0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
array = array+1

In [22]:
array

array([[1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
type(array[0][0])

numpy.float64

In [26]:
array

array([[1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 4., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
array1 = np.random.standard_normal((100,100))

In [29]:
array1[:2,:10]

array([[-1.58040806, -1.56053337, -1.05953499,  0.29898887,  0.48522896,
        -0.76813558,  1.76651136, -0.09324945,  0.90228387, -1.40617536],
       [ 1.17928768,  0.09472804,  1.24711097,  0.1152287 ,  1.1225599 ,
         1.0752186 , -1.74490986,  0.2696587 ,  0.15281223, -0.59031312]])

In [30]:
array1.astype(int)

array([[-1, -1, -1, ...,  0,  0,  0],
       [ 1,  0,  1, ...,  2,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       ...,
       [ 0,  1,  2, ...,  2,  0,  0],
       [ 0, -1,  1, ...,  0,  0,  0],
       [ 0, -1,  0, ...,  0,  0, -1]])

In [31]:
array[1,1] = np.nan

In [32]:
array

array([[ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1., nan,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [33]:
array


array([[ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1., nan,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  4.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [34]:
array = np.random.standard_normal((100,100))

In [35]:
array


array([[ 1.03244461,  0.53542245,  0.97199532, ..., -0.34347095,
         0.59995348,  0.1122486 ],
       [ 0.88111418, -0.23526689, -0.65855078, ...,  0.36995132,
        -0.67583934, -1.14467398],
       [-1.01163865, -0.16530609,  0.57299726, ..., -1.46776877,
        -0.40521307,  0.34068774],
       ...,
       [ 2.5266683 ,  0.13391111, -1.07485095, ...,  0.99031472,
         0.22331649, -0.6795894 ],
       [-1.05343681,  1.4988965 , -1.03822404, ..., -1.56287382,
         0.79255509, -0.21714484],
       [ 0.07995267, -0.15473243, -0.69224951, ..., -0.72371924,
         0.06124753, -1.15653739]])

In [36]:
array>0

array([[ True,  True,  True, ..., False,  True,  True],
       [ True, False, False, ...,  True, False, False],
       [False, False,  True, ..., False, False,  True],
       ...,
       [ True,  True, False, ...,  True,  True, False],
       [False,  True, False, ..., False,  True, False],
       [ True, False, False, ..., False,  True, False]])

In [37]:
array

array([[ 1.03244461,  0.53542245,  0.97199532, ..., -0.34347095,
         0.59995348,  0.1122486 ],
       [ 0.88111418, -0.23526689, -0.65855078, ...,  0.36995132,
        -0.67583934, -1.14467398],
       [-1.01163865, -0.16530609,  0.57299726, ..., -1.46776877,
        -0.40521307,  0.34068774],
       ...,
       [ 2.5266683 ,  0.13391111, -1.07485095, ...,  0.99031472,
         0.22331649, -0.6795894 ],
       [-1.05343681,  1.4988965 , -1.03822404, ..., -1.56287382,
         0.79255509, -0.21714484],
       [ 0.07995267, -0.15473243, -0.69224951, ..., -0.72371924,
         0.06124753, -1.15653739]])

In [38]:
array


array([[ 1.03244461,  0.53542245,  0.97199532, ..., -0.34347095,
         0.59995348,  0.1122486 ],
       [ 0.88111418, -0.23526689, -0.65855078, ...,  0.36995132,
        -0.67583934, -1.14467398],
       [-1.01163865, -0.16530609,  0.57299726, ..., -1.46776877,
        -0.40521307,  0.34068774],
       ...,
       [ 2.5266683 ,  0.13391111, -1.07485095, ...,  0.99031472,
         0.22331649, -0.6795894 ],
       [-1.05343681,  1.4988965 , -1.03822404, ..., -1.56287382,
         0.79255509, -0.21714484],
       [ 0.07995267, -0.15473243, -0.69224951, ..., -0.72371924,
         0.06124753, -1.15653739]])

In [39]:
array1 = array[1,:5]

In [40]:
array2 = array[1,-5:]

In [41]:
array1,array2

(array([ 0.88111418, -0.23526689, -0.65855078,  2.23495526,  0.0446078 ]),
 array([-1.31429659,  0.64732969,  0.36995132, -0.67583934, -1.14467398]))

In [42]:
np.maximum(array1,array2)

array([0.88111418, 0.64732969, 0.36995132, 2.23495526, 0.0446078 ])

In [44]:
array = np.zeros((6,5))
array[:,:] = 1
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
array[:,1] = 2

In [46]:
array

array([[1., 2., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 2., 1., 1., 1.]])

In [55]:
from __future__ import print_function

import os
import sys
# 使用insert 0即只使用github，避免交叉使用了pip安装的abupy，导致的版本不一致问题
sys.path.insert(0, os.path.abspath('../'))
import abupy
# 使用沙盒数据
abupy.env.enable_example_env_ipython()

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


plt.rcParams['figure.figsize'] = (10.0, 8.0)
from abupy import ABuSymbolPd
tesla_df = ABuSymbolPd.make_kl_df("TSLA",n_folds=2)

ValueError: source code string cannot contain null bytes